import type { MenuItem } from "@/lib/repositories/types";

// Using picsum.photos with a fixed seed per item so images are stable
// across reloads without needing to host real food photography for a demo.
function img(seed: string) {
  return `https://picsum.photos/seed/${seed}/480/320`;
}

export const MENU_SEED: MenuItem[] = [
  {
    id: "menu_margherita",
    name: "Margherita Pizza",
    description: "San Marzano tomato, fresh mozzarella, basil, olive oil.",
    priceCents: 1299,
    imageUrl: img("margherita"),
    category: "Pizza",
    isAvailable: true,
  },
  {
    id: "menu_pepperoni",
    name: "Pepperoni Pizza",
    description: "Classic pepperoni with a blend of mozzarella and provolone.",
    priceCents: 1499,
    imageUrl: img("pepperoni"),
    category: "Pizza",
    isAvailable: true,
  },
  {
    id: "menu_veggie_supreme",
    name: "Veggie Supreme Pizza",
    description: "Bell peppers, onion, mushroom, olives, sweet corn.",
    priceCents: 1399,
    imageUrl: img("veggie-supreme"),
    category: "Pizza",
    isAvailable: true,
  },
  {
    id: "menu_classic_burger",
    name: "Classic Cheeseburger",
    description: "Beef patty, cheddar, lettuce, tomato, house sauce.",
    priceCents: 899,
    imageUrl: img("classic-burger"),
    category: "Burgers",
    isAvailable: true,
  },
  {
    id: "menu_veg_burger",
    name: "Crispy Veg Burger",
    description: "Herbed potato-pea patty, slaw, chipotle mayo.",
    priceCents: 799,
    imageUrl: img("veg-burger"),
    category: "Burgers",
    isAvailable: true,
  },
  {
    id: "menu_double_smash",
    name: "Double Smash Burger",
    description: "Two smashed patties, American cheese, pickles, onion.",
    priceCents: 1099,
    imageUrl: img("double-smash"),
    category: "Burgers",
    isAvailable: true,
  },
  {
    id: "menu_caesar_salad",
    name: "Chicken Caesar Salad",
    description: "Grilled chicken, romaine, parmesan, garlic croutons.",
    priceCents: 999,
    imageUrl: img("caesar-salad"),
    category: "Salads",
    isAvailable: true,
  },
  {
    id: "menu_greek_salad",
    name: "Greek Salad",
    description: "Cucumber, tomato, feta, kalamata olives, oregano.",
    priceCents: 849,
    imageUrl: img("greek-salad"),
    category: "Salads",
    isAvailable: true,
  },
  {
    id: "menu_loaded_fries",
    name: "Loaded Fries",
    description: "Crispy fries, cheese sauce, jalapeños, spring onion.",
    priceCents: 599,
    imageUrl: img("loaded-fries"),
    category: "Sides",
    isAvailable: true,
  },
  {
    id: "menu_onion_rings",
    name: "Beer-Battered Onion Rings",
    description: "Thick-cut onion rings, crisp batter, smoky dip.",
    priceCents: 549,
    imageUrl: img("onion-rings"),
    category: "Sides",
    isAvailable: true,
  },
  {
    id: "menu_lemonade",
    name: "Fresh Mint Lemonade",
    description: "Cold-pressed lemon, mint, a touch of honey.",
    priceCents: 349,
    imageUrl: img("lemonade"),
    category: "Drinks",
    isAvailable: true,
  },
  {
    id: "menu_cold_brew",
    name: "Cold Brew Coffee",
    description: "18-hour slow-steeped, served over ice.",
    priceCents: 399,
    imageUrl: img("cold-brew"),
    category: "Drinks",
    isAvailable: true,
  },
  {
    id: "menu_brownie",
    name: "Fudge Brownie",
    description: "Dense dark-chocolate brownie, sea salt flake.",
    priceCents: 449,
    imageUrl: img("brownie"),
    category: "Desserts",
    isAvailable: true,
  },
  {
    id: "menu_churros",
    name: "Cinnamon Churros",
    description: "Six pieces, cinnamon sugar, chocolate dip.",
    priceCents: 499,
    imageUrl: img("churros"),
    category: "Desserts",
    isAvailable: true,
  },
  {
    id: "menu_tiramisu",
    name: "Tiramisu Cup",
    description: "Espresso-soaked ladyfingers, mascarpone, cocoa dust.",
    priceCents: 549,
    imageUrl: img("tiramisu"),
    category: "Desserts",
    isAvailable: true,
  },
  {
    id: "menu_chicken_wrap",
    name: "Grilled Chicken Wrap",
    description: "Peri-peri chicken, lettuce, garlic mayo, tortilla.",
    priceCents: 749,
    imageUrl: img("chicken-wrap"),
    category: "Wraps",
    isAvailable: true,
  },
  {
    id: "menu_falafel_wrap",
    name: "Falafel Wrap",
    description: "Crispy falafel, hummus, pickled turnip, tahini.",
    priceCents: 699,
    imageUrl: img("falafel-wrap"),
    category: "Wraps",
    isAvailable: true,
  },
  {
    id: "menu_paneer_wrap",
    name: "Tandoori Paneer Wrap",
    description: "Char-grilled paneer, mint chutney, red onion.",
    priceCents: 729,
    imageUrl: img("paneer-wrap"),
    category: "Wraps",
    isAvailable: true,
  },
  {
    id: "menu_alfredo",
    name: "Fettuccine Alfredo",
    description: "Parmesan cream sauce, cracked black pepper.",
    priceCents: 1149,
    imageUrl: img("alfredo"),
    category: "Pasta",
    isAvailable: true,
  },
  {
    id: "menu_arrabbiata",
    name: "Penne Arrabbiata",
    description: "Spicy tomato sauce, garlic, chili flakes, basil.",
    priceCents: 1099,
    imageUrl: img("arrabbiata"),
    category: "Pasta",
    isAvailable: true,
  },
  {
    id: "menu_carbonara",
    name: "Spaghetti Carbonara",
    description: "Guanciale, egg yolk, pecorino, black pepper.",
    priceCents: 1199,
    imageUrl: img("carbonara"),
    category: "Pasta",
    isAvailable: true,
  },
  {
    id: "menu_teriyaki_bowl",
    name: "Chicken Teriyaki Bowl",
    description: "Steamed rice, teriyaki chicken, sesame, scallion.",
    priceCents: 999,
    imageUrl: img("teriyaki-bowl"),
    category: "Rice Bowls",
    isAvailable: true,
  },
  {
    id: "menu_burrito_bowl",
    name: "Burrito Bowl",
    description: "Cilantro rice, black beans, salsa, guacamole, corn.",
    priceCents: 949,
    imageUrl: img("burrito-bowl"),
    category: "Rice Bowls",
    isAvailable: true,
  },
  {
    id: "menu_poke_bowl",
    name: "Spicy Tuna Poke Bowl",
    description: "Sushi rice, tuna, edamame, avocado, spicy mayo.",
    priceCents: 1249,
    imageUrl: img("poke-bowl"),
    category: "Rice Bowls",
    isAvailable: true,
  },
  {
    id: "menu_tomato_soup",
    name: "Roasted Tomato Soup",
    description: "Slow-roasted tomato, basil oil, garlic crouton.",
    priceCents: 649,
    imageUrl: img("tomato-soup"),
    category: "Soups",
    isAvailable: true,
  },
  {
    id: "menu_miso_soup",
    name: "Miso Soup",
    description: "Tofu, wakame seaweed, scallion, dashi broth.",
    priceCents: 599,
    imageUrl: img("miso-soup"),
    category: "Soups",
    isAvailable: true,
  },
  {
    id: "menu_iced_tea",
    name: "Peach Iced Tea",
    description: "Black tea, fresh peach, light syrup, over ice.",
    priceCents: 349,
    imageUrl: img("iced-tea"),
    category: "Drinks",
    isAvailable: true,
  },
  {
    id: "menu_mango_smoothie",
    name: "Mango Smoothie",
    description: "Alphonso mango, yogurt, a hint of cardamom.",
    priceCents: 449,
    imageUrl: img("mango-smoothie"),
    category: "Drinks",
    isAvailable: true,
  },
  {
    id: "menu_garlic_bread",
    name: "Garlic Cheese Bread",
    description: "Toasted baguette, garlic butter, mozzarella.",
    priceCents: 499,
    imageUrl: img("garlic-bread"),
    category: "Sides",
    isAvailable: true,
  },
];
